[project]
name = "ptz-controler"
version = "0.1.0"
description = "PTZ Controller"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "textual>=8.2.6",
    "textual-web>=0.4.2",
    "visca-over-ip",
]

[tool.uv.sources]
visca-over-ip = { git = "https://github.com/misterhay/VISCA-IP-Controller.git", rev = "0bf2af1baeee3f603f1c75f69162eb5124b9be73" }
